#!/bin/bash
# Usage: script/start
# Starts the project's development server.
# not used in Nitrous Build

set -e errexit

tsc ./src/mainmodule.ts ./src/main.ts ./src/bootstrap.ts --module AMD --outDir ./app/lib

node ./script/lib/server.js --port=3000 --verbose --root ./app