#!/bin/bash
# Usage: script/start
# Starts the project's development server.
# not used in Nitrous Build

set -e errexit

find ./src -name '*.ts' -type f > tsc.txt
tsc @tsc.txt --module AMD --outDir ./app/lib
rm tsc.txt

node ./script/lib/server.js --port=3000 --verbose --root ./app